site_name: Static Docs Demo
site_url: https://alex-arce.github.io/mkdocs-demo
nav:
    - Home: index.md
    - Architecture: architecture.md
    - Software: software.md
    - Networking: networking.md
    - Misc: misc.md
    - About: about.md
theme: material
#theme: readthedocs
