name: Build and Deploy MkDocs project to Local Nginx

on:
  push:
    branches:
      - main

jobs:
  local-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: Build site
        run: mkdocs build
      
      - name: Deploy to local nginx
        run: |
          cp -Rf /home/alea/actions-runner/_work/mkdocs-demo/mkdocs-demo/site /var/www/html
